language: node_js

sudo: false

cache:
  apt: true
  dirctories:
    - node_modules

node_js: stable

install:
  - npm install -D
  - cd ./test/smoke/template
  # - cd .
  - npm install -D
  - cd ../../../

scripts:
  - npm test
