language:node_js

sudo:false

cache:node_js
  apt:true
  dirctories:
    - node_modules

node_js:stable

install:
  - npm install -D
  # - cd ./test/smoke/template
   - cd .
  - npm install -D

scripts:
  - npm test